chore: update for Gatsby v5
ChappIO/gatsby-remark-mermaid pull request #19
Opened 2022-11-12 23:54 UTC by bdenham

## Description

This PR provides the following updates:

- Updates `mermaid.js` to the latest version. 
- Adds `puppeteer-core` as a peer dependency.
- Updates `npm install` command to add `puppeteer` and `puppeteer-core` as `devDependencies`.

NOTE: Gatsby v5 projects required `puppeteer-core` to be listed explicitly in `devDependencies` along with `puppeteer`.

## Testing

Updates to the package were manually tested in both Gatsby v4 and v5 projects:

- Gatsby v5 MDX starter project
- Gatsby v4.24  theme project 

In both projects, I used [yalc](https://www.npmjs.com/package/yalc) to test my local package changes to ensure I could successfully render the same markdown file (see below) of all the mermaid diagrams currently supported on [https://mermaid.live/](https://mermaid.live/):

- Sequence
- Flow
- Class
- State
- ER
- Gantt
- User Journey
- Git

### Gatsby v5 MDX starter project

The test markdown file was added to the Gatsby v5 starter project using both `.md` and `.mdx` extensions. All diagrams rendered correctly, matching the output shown on [https://mermaid.live/](https://mermaid.live/). All plugin options worked as designed using the following configuration:

```js
{
  resolve: 'gatsby-remark-mermaid',
  options: {
    language: 'mermaid',
    theme: 'base',
    viewport: {
      width: 1280,
      height: 800
    },
    mermaidOptions: {
      themeVariables: mermaidThemeVariables,
      themeCSS: mermaidThemeCSS,
      flowchart: flowchart,
    },
  },
},
```

### Gatsby v4.24  theme project

The test markdown file was added to the Gatsby v4.24 example project within the theme's monorepo. All diagrams rendered correctly, matching the output shown on [https://mermaid.live/](https://mermaid.live/). All plugin options worked as designed using the same configuration noted above.

## Markdown Test File

<details><summary>MARKDOWN TEST FILE — Edit this description to copy it.</summary>

# Mermaid Tests

This is a test page for mermaid diagrams.

## Flowchart

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

## Sequence Diagrams

### From Live Editor

  ```mermaid
  sequenceDiagram
      Alice->>+John: Hello John, how are you?
      Alice->>+John: John, can you hear me?
      John-->>-Alice: Hi Alice, I can hear you!
      John-->>-Alice: I feel great!
  ```

### With loop

```mermaid
sequenceDiagram
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts!
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good!
```

## Gantt Diagram

```mermaid
gantt
    dateFormat  YYYY-MM-DD
    title Adding GANTT diagram functionality to mermaid

    section A section
    Completed task            :done,    des1, 2014-01-06,2014-01-08
    Active task               :active,  des2, 2014-01-09, 3d
    Future task               :         des3, after des2, 5d
    Future task2              :         des4, after des3, 5d

    section Critical tasks
    Completed task in the critical line :crit, done, 2014-01-06,24h
    Implement parser and jison          :crit, done, after des1, 2d
    Create tests for parser             :crit, active, 3d
    Future task in critical line        :crit, 5d
    Create tests for renderer           :2d
    Add to mermaid                      :1d

    section Documentation
    Describe gantt syntax               :active, a1, after des1, 3d
    Add gantt diagram to demo page      :after a1  , 20h
    Add another diagram to demo page    :doc1, after a1  , 48h

    section Last section
    Describe gantt syntax               :after doc1, 3d
    Add gantt diagram to demo page      : 20h
    Add another diagram to demo page    : 48h
```

## Class Diagram

```mermaid
classDiagram
    Animal <|-- Duck
    Animal <|-- Fish
    Animal <|-- Zebra
    Animal : +int age

    Animal : +String getSpecies()
    Animal : +void eat()
    class Duck{
        +String beakColor
        +swim()
        +quack()
    }
    class Fish{
        -int sizeInFeet
        -canEat()
    }
    class Zebra{
        +bool is_wild
        +run()
    }
```

## State Diagram

```mermaid
stateDiagram
    [*] --> Still
    Still --> [*]

    Still --> Moving
    Moving --> Still
    Moving --> Crash
    Crash --> [*]
```

## Pie Chart

```mermaid

pie
    title Key elements in Product X
    "Calcium" : 42.96
    "Potassium" : 50.05
    "Magnesium" : 10.01
    "Iron" :  5
```

## Git Graph

```mermaid
gitGraph
    commit
    commit
    branch develop
    checkout develop
    commit
    commit
    checkout main
    merge develop
    commit
    commit
```

## User Journey

```mermaid
journey
    title My working day
    section Go to work
      Make tea: 5: Me
      Go upstairs: 3: Me
      Do work: 1: Me, Cat
    section Go home
      Go downstairs: 5: Me
      Sit down: 5: Me
```

## Entity Relationship Diagram

```mermaid
erDiagram
    CUSTOMER }|..|{ DELIVERY-ADDRESS : has
    CUSTOMER ||--o{ ORDER : places
    CUSTOMER ||--|{ INVOICE : "liable for"
    DELIVERY-ADDRESS ||--o{ ORDER : receives
    INVOICE ||--|{ ORDER : covers
    ORDER ||--|{ ORDER-ITEM : includes
    PRODUCT-CATEGORY ||--|{ PRODUCT : contains
    PRODUCT ||--o{ ORDER-ITEM : "ordered in"
```
</details>

2022-11-16 12:04 UTC, remcohaszing commented
I suggest to revamp this plugin entirely using [`remark-mermaidjs`](https://github.com/remcohaszing/remark-mermaidjs) instead.

I think all that’s needed is the following code:

```js
async function gatsbyRemarkMermaid(ast, options) {
  const { default: plugin } = await import('remark-mermaidjs')
  const transformer = plugin(options)
  return transformer(ast)
}

module.exports = gatsbyRemarkMermaid
```

Could you give that a try?

Technically the transformer takes a second argument `vfile`, but I’m not sure how to retrieve it from the gatsby interface and it’s unused by `remark-mermaidjs`.

2022-11-19 16:24 UTC, bdenham commented
@remcohaszing: Take a look. Using `remark-mermaidjs` keeps this plugin pretty simple. I do have a suggestion to for updating `remark-mermaidjs` so we could pass in some custom viewport settings that would look something like this when configuring this plugin on the Gatsby side of things:

```
{
  resolve: `gatsby-remark-mermaid`,
  options: {
    launchOptions: {
      executablePath: puppeteer.executablePath(),
      defaultViewport: {
        width: 1280,
        height: 3000,
      }
    },
  }
}
```

2022-11-21 11:13 UTC, remcohaszing requested changes
Thank you! This looks really great!

I just have a few nit picks.

2022-11-21 11:13 UTC, remcohaszing commented on README.md
> +Creates [mermaid](https://mermaidjs.github.io/) graphs and diagrams in your markdown files.
I prefer an imperative style tag line.

```suggestion
Create [mermaid](https://mermaidjs.github.io/) graphs and diagrams in your markdown files.
```

2022-11-21 11:13 UTC, remcohaszing commented on README.md
> +This plugin uses [remark-mermaidjs](https://github.com/remcohaszing/remark-mermaidjs) to generate SVG diagrams at build-time. The mermaid code blocks are replaced with an inline SVGs in the generated
```suggestion
This plugin uses [remark-mermaidjs](https://github.com/remcohaszing/remark-mermaidjs) to generate SVG diagrams at build time. The mermaid code blocks are replaced with an inline SVG in the generated HTML. This prevents any runtime
```

2022-11-21 11:13 UTC, remcohaszing commented on README.md
> +```bash
```suggestion
```sh
```

2022-11-21 11:13 UTC, remcohaszing commented on README.md
> +## How to use
Thank you for structuring the readme!

I’ve been trying to use a more consistent readme layout across my repositories, including consistent headers.

```suggestion
## Usage
```

2022-11-21 11:13 UTC, remcohaszing commented on README.md
> +plugins: [
Let’s provide fully valid JavaScript, including:

```js
module.exports = {
  // …
}
```

2022-11-21 11:13 UTC, remcohaszing commented on README.md
> +## Configuration Options
```suggestion
## Options
```

2022-11-21 11:13 UTC, remcohaszing commented on README.md
> +| `launchOptions.executablePath`  | `""`                 | (Required) String path to the chrome executable that puppeteer uses to render the mermaid diagrams to SVGs.
This option has no default value.

```suggestion
| `launchOptions.executablePath`  |                      | (Required) String path to the chrome executable that puppeteer uses to render the mermaid diagrams to SVGs.                                                                                                                                                               |
```

2022-11-21 11:13 UTC, remcohaszing commented on README.md
> +| `svgo.plugins`                  | `defaultSVGOOptions` | (Optional) Override default optimizations for the generated SVG files. Set to `null` to disable minifying using SVGO completely. See [defaul
```suggestion
| `svgo.plugins`                  | `defaultSVGOOptions` | (Optional) Override default optimizations for the generated SVG files. Set to `null` to disable minifying using SVGO completely. See [defaultSVGOOptions](https://github.com/remcohaszing/remark-mermaidjs/blob/v4.0.0/index.ts#L18)).) |
```

2022-11-21 11:13 UTC, remcohaszing commented on package.json
> +  "version": "2.2.0",
Could you revert this version? This is part of the release process. It should not be part of a PR.

```suggestion
  "version": "2.1.0",
```

2022-11-21 11:13 UTC, remcohaszing commented on package.json
> +}
```suggestion
}

```

2022-11-21 11:13 UTC, remcohaszing commented on package.json
> +    "remark-mermaidjs": "^3.1.0"
I just created a new release of `remark-mermaidjs`. Let’s use that here. It works pretty much the same ([release notes](https://github.com/remcohaszing/remark-mermaidjs/releases/tag/v4.0.0))

```suggestion
    "remark-mermaidjs": "^4.0.0"
```

2022-11-21 17:35 UTC, bdenham commented
@remcohaszing: Great review! It's a true pleasure to work with someone who pays attention to detail!

2022-11-21 20:05 UTC, remcohaszing commented
Awesome! Thank you! :heart:

2022-11-21 20:08 UTC, merged

2022-11-21 21:01 UTC, bdenham commented
Thanks, @remcohaszing! I look forward to working with you more in the future!

2022-11-21 21:23 UTC, remcohaszing commented
Aww thanks! I’m sure we will if you stay around in the remark / MDX ecosystem. :)